### ISSUE TITLE
Reorganizar el material multimedia

### ISSUE THREAD

**Issue by jgomo3** [pyve/pyve.github.com#37]
1) La página tiene varias imágenes.
2) Existe un repositorio de materiales de eventos.

Propuesta: Colocar las imágenes relacionadas con eventos (fotos) en el repositorio dedicado a tal fin, y dejar en la página solamente enlaces a las fotos.

Propuesta adicional: Conseguir un servicio más adecuado para mantener un repositorio de contenido multimedia que no sea GitHub.

**Comment by atmantree** [comment]
vale, me parece apropiado para tener en cuenta para el rediseño del sitio web.

**Comment by ngodoy** [comment]
se decidió ala final que con framework  trabajáremos ¿

**Comment by jackboot7** [comment]
@ngodoy  hay una propuesta para usar `Lektor`. Se ha estado hablando de ello en el canal de slack https://pyve.slack.com/messages/pyve-website/

También hay una primera propuesta de diseño.

**Comment by hernanramirez** [comment]
Debemos cerrar esto.. ya no aplica
