### ISSUE TITLE
[BUG] Pythonistas de Venezuela. (Template no real)

### ISSUE THREAD

**Issue by nhomar** [pyve/pyve.github.com#47]
Hola.

La sección de Pythonistas solo tiene el template podemos usar un widgetsito js simple como lo teníamos en la versión anterior.

**Ahora:**

![](https://www.evernote.com/l/AJ7jMiWoWbdO4ah2QLtTsVq4GvHn1_tc4LYB/image.png)

[**Puedes ver la version anterior aquí-:**](http://pyve.github.io/index_old.html)

**Comment by mamcode** [comment]
Si este no me terminaba de convencer, está algo fumado, por acá hay un ejemplo de otro que podríamos usar http://bootdey.com/snippets/view/List-user-profiles personalizandolo pa ponerlo más seriesito, pero también podríamos usar el anterior que está en la rama master. Decidamos y le damos play...

**Comment by mamcode** [comment]
Lo de pinga del que ya tenemos en la rama master (el primero) es que ya esta el js para crear dinámicamente los avatars desde github, aunque esto no es una limitante nos ahorra tiempo.

**Comment by nhomar** [comment]
Esto lo considero cerrado ya está fino!

Cualquier cosa que se necesite con el look and feel se deberá tratar en otro issue
