### ISSUE TITLE
[Contenido] Hacer el menú y la página responsive

### ISSUE THREAD

**Issue by hernanramirez** [pyve/pyve.github.com#49]
Hacer la pagina responsive, para tener mejor visualización en moviles

**Comment by hernanramirez** [comment]
Se debe hacer ajuste al css para que los botones tengan el primar diseño de manuel.

Lleve el menú al standart de bootstap haciéndolo  responsive

**Comment by hernanramirez** [comment]
Hice un PR con propuesta pero hace falta mejorar el CSS

**Comment by mamcode** [comment]
Con el PR #55 ya hay un avance importante en este tema, toca revisar que mas se puede mejorar para hacer el sitio mas responsive.
