### ISSUE TITLE
[Estrctura] Comunidad/Eventos

### ISSUE THREAD

**Issue by hernanramirez** [pyve/pyve.github.com#50]
Recomendaría hacer otro botón para separar el contenido actual de comunidades y eventos

**Comment by mamcode** [comment]
Me parece bien @hernanramirez aunque en un futuro podriamos cambiar el menu dropdown sugerido en el PR #55 por un boton normalito porque cada vez que haya un evento se va a ir incrementando esa lista, pero por ahora me parece que esta bien :+1:

**Comment by hernanramirez** [comment]
Pienso que será automático al momento de migrar a django. Estará en dB y será dinamico
