### ISSUE TITLE
Hacer página de Contacto

### ISSUE THREAD

**Issue by hernanramirez** [pyve/pyve.github.com#52]

**Comment by nhomar** [comment]
Esta página debería apuntar a un isue público en Github.... según yo... o al correo de la lista.

**Comment by hernanramirez** [comment]
Mejor coloca los link a lista y redes sociales

**Comment by nhomar** [comment]
@hernanramirez me parece bien ... entonces así será

**Comment by mamcode** [comment]
Esta fina la idea de que se envie un mensaje a la lista. Podria ser a traves de un form que se coloque en la pagina.
