### ISSUE TITLE
[FIX] No perder la historia

### ISSUE THREAD

**Issue by nhomar** [pyve/pyve.github.com#58]
Sería buenoque la historia no se pierda, los eventos viejos tienen sus archivos listos para mostrar en el formato viejo, pero listos, sería bueno agregarle su enlace.

![](https://www.evernote.com/l/AJ7XsfvR5RpER5OQhT7SvipcZrcMz-LK_QgB/image.png)

**Comment by hernanramirez** [comment]
Buena idea.. quizas sea buena idea adaptalo al nuevo formato... de momento se puede colocar el link. Solo se movieron al directorio eventos
