### ISSUE TITLE
Agregar links faltantes en la sección features de la homepage

### ISSUE THREAD

**Issue by satanas** [pyve/pyve.github.com#68]
Depende de que se terminen páginas faltantes

**Comment by jackboot7** [comment]
@satanas  te refieres al mismo asunto que se trata en el  #64 ? Si es así, cerremos este issue.

**Comment by satanas** [comment]
Sí, al parecer es lo mismo. Se me pasó cuando pasé la lista de las tareas que aparecen en el README a issues de github, así que cierro este y seguimos con el #64
