### ISSUE TITLE
Crear página para integrantes de la comunidad

### ISSUE THREAD

**Issue by satanas** [pyve/pyve.github.com#77]
Con información de nuestros perfiles (avatar, twitter, repo de github, usuario de stackoverflow, etc)

**Comment by atmantree** [comment]
Según recuerdo los perfiles en la página anterior se sacaban mediante un hook o algo con la api de GH. No se que se requiera para tener algo automatizado, pero capaz podemos copiarnos la idea de Ubuntu-VE y que cada quien tenga su página personal en la Wiki (en nuestro caso, del repo).

**Comment by atmantree** [comment]
acá el código que lo hacía en la página anterior [pyve.js](https://github.com/sebasmagri/pyve.github.com/blob/40a1c9aed3555f240556b8b2bc82a85e60861690/js/pyve.js)

**Comment by jackboot7** [comment]
En teoría, más allá de los estilos, no debería haber problema al usar ese mismo código.

**Comment by atmantree** [comment]
señores, se que es fácil darle al botón de merge, pero por favor revisen..
y en caso de dudas pregunten o comenten..

2016-02-04 13:38 GMT-04:30 Nhomar Hernández [Vauxoo] <
notifications@github.com>:
