### ISSUE TITLE
Crear página con instrucciones para registrarse en la lista de correos

### ISSUE THREAD

**Issue by satanas** [pyve/pyve.github.com#84]

**Comment by jgomo3** [comment]
Al principio creí que no tenía sentido crear esta página que propones porque cualquier cosa que deba decirse se podría haber dicho durante el registro en la lista.

Pero la lista de googlegroups no me permite definir un buen mensaje de "aceptación de términos" para unirse.

Así que hasta ahora, hice esto:

"""
https://groups.google.com/forum/#!forum/python-venezuela

Básicamente añadí un enlace al documento "Reglas de etiqueta en la
lista de correos de Python Venezuela"[1], cambié el enlace a [2]¿Cómo
hacer una oferta de empleo en la lista de correos de Python
Venezuela?[2] por uno a la "Cartelera de Empleos"[3] (Con la idea de
que en esa cartelera se haga referencia a [2]).

La intención es que las ofertas de empleo se registren en ese lugar. A
su vez, crear en la página de pyve una sección de empleo que incluya
la información recolectada por laaplicación[3]: Muy parecido a lo que
tiene la página de python.org actualmente[4].

[1] https://github.com/pyve/documentos/blob/master/reglas-de-etiqueta-en-la-lista-de-correo.md
[2] https://github.com/pyve/documentos/blob/master/como-hacer-ofertas-de-empleo.md
[3] https://pyve.github.io/empleos/
[4] https://www.python.org/jobs/
"""
